import Head from 'next/head';
import Posts from '../components/posts/Index';
import githubAxiosInstance from 'utils/GithubAxiosInstance';
import { GetServerSideProps } from 'next';

const Home = ({ posts }) => {

  return (
    <div>
      <Head>
        <title> typeof just.in . A website by Justin George </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div>
        <Posts 
          posts={posts}
        />
      </div>

    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await githubAxiosInstance.get(`issues?state=closed`)
  return {
    props: { posts: data }
  }
}

export default Home;