import Head from 'next/head';
import Posts from '../components/posts/Index';
import githubAxiosInstance from 'utils/GithubAxiosInstance';
import { GetServerSideProps } from 'next';

const Home = ({ posts }) => {

  return (
    <div>
      <Head>
        <title> typeof just.in . A website by Justin George </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Introduction />

      <div>
        <h2 className='text-5xl mb-6 font-extralight text-purple-600'> Stuffs that I wrote </h2>
        <Posts 
          posts={posts}
        />
      </div>

    </div>
  )
}

const Introduction = () => (
  <div className='text-xl font-light mb-8'>
    <p className='inline'>Hello, </p> 
    <h1 className='text-3xl inline'> I'm Justin George.</h1>
    <p className='inline'> A software professional working on JavaScript, React, Node.js </p>
  </div>
)

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await githubAxiosInstance.get(`issues?state=closed`)
  return {
    props: { posts: data }
  }
}

export default Home;